export const actionTypes = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',

  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',

  ADD_TO_CART: 'ADD_TO_CART',
  INCREMENT_PRODUCT: 'INCREMENT_PRODUCT',
  DECREMENT_PRODUCT: 'DECREMENT_PRODUCT',
  CLEAR_CART: 'CLEAR_CART',
  SEND_ORDER: 'SEND_ORDER',

  ADD_STREET: 'ADD_STREET',
  ADD_HOME: 'ADD_HOME',

  CHECK_SELECTOR: 'CHECK_SELECTOR',

  ERROR: 'ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};
